@EmployeeManagement_HostAddress = http://localhost:5125

### Create Employee
POST {{EmployeeManagement_HostAddress}}/api/employees
Content-Type: application/json

{
  "name": "Satya Mishra",
  "email": "satya@example.com",
  "department": "IT",
  "salary": 50000
}

### Get All Employees
GET {{EmployeeManagement_HostAddress}}/api/employees
Accept: application/json