@EmployeeManagement_HostAddress = http://localhost:5125

### Create Employee
POST {{EmployeeManagement_HostAddress}}/api/employees
Content-Type: application/json

{
  "name": "Satya Mishra",
  "email": "satya@example.com",
  "department": "IT",
  "salary": 50000
}

### Get All Employees
GET {{EmployeeManagement_HostAddress}}/api/employees
Accept: application/json

### Update Employee
PUT {{EmployeeManagement_HostAddress}}/api/employees/1
Content-Type: application/json

{
  "name": "Satya Mishra Updated",
  "email": "satya.updated@example.com",
  "department": "Software Development",
  "salary": 60000
}

### Delete Employee
DELETE {{EmployeeManagement_HostAddress}}/api/employees/1

### Create Employee
POST {{EmployeeManagement_HostAddress}}/api/employees
Content-Type: application/json

{
  "name": "Rahul Sharma",
  "email": "rahul@example.com",
  "department": "IT",
  "salary": 55000
}

### Get Employee By ID
GET {{EmployeeManagement_HostAddress}}/api/employees/2
Accept: application/json

### Test Invalid Employee
POST {{EmployeeManagement_HostAddress}}/api/employees
Content-Type: application/json

{
  "name": "",
  "email": "wrong-email",
  "department": "",
  "salary": -5000
}

### Test Create Employee - 201 Created
POST {{EmployeeManagement_HostAddress}}/api/employees
Content-Type: application/json

{
  "name": "Aman Verma",
  "email": "aman@example.com",
  "department": "Development",
  "salary": 65000
}

### Test Employee Not Found
GET {{EmployeeManagement_HostAddress}}/api/employees/9999
Accept: application/json

### Test Update Non-Existing Employee
PUT {{EmployeeManagement_HostAddress}}/api/employees/9999
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "department": "IT",
  "salary": 50000
}

### Test Delete Non-Existing Employee
DELETE {{EmployeeManagement_HostAddress}}/api/employees/9999

### Get employees with JWT
GET http://localhost:5125/api/Employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzYXR5YUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJzYXR5YSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3ODk4NDIwMjYsImlzcyI6IkVtcGxveWVlTWFuYWdlbWVudEFQSSIsImF1ZCI6IkVtcGxveWVlTWFuYWdlbWVudENsaWVudCJ9.IBS6yRpXCuIS3zTjkFxHwWMEjg325IF3zS9_PEz6-z0